### ISSUE TITLE
tpch-dbgen: request for CI migration

### ISSUE THREAD

**Issue by davidkhala** [eyalroz/tpch-dbgen#35]
It has been a while since my last time using your repository github.com/eyalroz/tpch-dbgen. While I am also a evangelist of CI, I see the trends of Travis CI becoming close minded.

So would you mind me creating a PR to migrate from travis.ci to Github workflow?

**Comment by eyalroz** [comment]
I'd definitely welcome it. I would have done it myself had I had more time on my hands. Go right ahead...
